name: Node.js CI
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version:
    #     # - 4.x
    #     # - 5.x
    #     # - 6.x
    #     # - 7.x
    #     # - 8.x
    #     # - 9.x
    #     # - 10.x
    #     # - 12.x
    #     # - 13.x
    #     # - 15.x
    #     - 19.x
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      # with:
      #   node-version: ${{ matrix.node-version }}
      #   cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
